config/routes.rb
LunchTimeNavi::Application.routes.draw do

  resources :congestions

  root :to => 'signup#signup'      

  resources :summary_lists, :only => [:index]

  resources :lunch_comments

  resources :genres

  resources :lunches

  resources :ratings

  resources :users

  resources :restaurants

  match 'signedup' => 'signup#signedup'
  match 'newUserRegistered' => 'signup#newUserRegistered'
  match 'signup/signup' => 'signup#signup'
  match 'signup/signedup' => 'signup#signedup'
  match 'signup/registerNewUser' => 'signup#registerNewUser'
  match 'signup/newUserRegistered' => 'signup#newUserRegistered'

  match 'lunch_comments/new2/:id' => 'lunch_comments#new2'
  match 'lunches/new2/:id' => 'lunches#new2'
  match 'restaurants/new2/:id' => 'restaurants#new2'
  match 'summary_lists/search' => 'summary_lists#search'

end

app/models/congestion.rb
class Congestion < ActiveRecord::Base
  attr_accessible :name, :value

  validates :name, :value, uniqueness: true
  validates :name, :value, presence: true
end

app/controllers/congestions_controller.rb
class CongestionsController < ApplicationController
  # GET /congestions
  # GET /congestions.json
  def index
    @congestions = Congestion.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @congestions }
    end
  end

  # GET /congestions/1
  # GET /congestions/1.json
  def show
    @congestion = Congestion.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @congestion }
    end
  end

  # GET /congestions/new
  # GET /congestions/new.json
  def new
    @congestion = Congestion.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @congestion }
    end
  end

  # GET /congestions/1/edit
  def edit
    @congestion = Congestion.find(params[:id])
  end

  # POST /congestions
  # POST /congestions.json
  def create
    @congestion = Congestion.new(params[:congestion])

    respond_to do |format|
      if @congestion.save
        format.html { redirect_to @congestion, notice: 'Congestion was successfully created.' }
        format.json { render json: @congestion, status: :created, location: @congestion }
      else
        format.html { render action: "new" }
        format.json { render json: @congestion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /congestions/1
  # PUT /congestions/1.json
  def update
    @congestion = Congestion.find(params[:id])

    respond_to do |format|
      if @congestion.update_attributes(params[:congestion])
        format.html { redirect_to @congestion, notice: 'Congestion was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @congestion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /congestions/1
  # DELETE /congestions/1.json
  def destroy
    @congestion = Congestion.find(params[:id])
    @congestion.destroy

    respond_to do |format|
      format.html { redirect_to congestions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/congestions_helper.rb
module CongestionsHelper
end

app/views/congestions/_form.html.erb
<%= form_for(@congestion) do |f| %>
  <% if @congestion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@congestion.errors.count, "error") %> prohibited this congestion from being saved:</h2>

      <ul>
      <% @congestion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.number_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/congestions/edit.html.erb
<h1>Editing congestion</h1>

<%= render 'form' %>

<%= link_to 'Show', @congestion %> |
<%= link_to 'Back', congestions_path %>

app/views/congestions/index.html.erb
<h1>Listing congestions</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @congestions.each do |congestion| %>
  <tr>
    <td><%= congestion.name %></td>
    <td><%= congestion.value %></td>
    <td><%= link_to 'Show', congestion %></td>
    <td><%= link_to 'Edit', edit_congestion_path(congestion) %></td>
    <td><%= link_to 'Destroy', congestion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Congestion', new_congestion_path %>

app/views/congestions/new.html.erb
<h1>New congestion</h1>

<%= render 'form' %>

<%= link_to 'Back', congestions_path %>

app/views/congestions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @congestion.name %>
</p>

<p>
  <b>Value:</b>
  <%= @congestion.value %>
</p>


<%= link_to 'Edit', edit_congestion_path(@congestion) %> |
<%= link_to 'Back', congestions_path %>